### ISSUE TITLE
pretrained model

### ISSUE THREAD

**Issue by boehm-e** [tdplaza/Tacotron_Prosody_multi_GPU#1]
Hi, 

Could you please upload the pretrained model ?

Thank you :)

**Comment by Thien223** [comment]
Sorry, my bad,
I did not well keep the pretrained model for this repository, to use this, you have to train from scratch.

So I will send you a little older version with pretrained model inside.

https://drive.google.com/file/d/1fxLLuwRgcnURH8jy36-dvUGWjgp20oc7/view

Running is exactly same. `python TacotronModel\Synthesize.py --mode=inference`. make sure your PYTHONPATH is correctly configured to refer local modules.

Cheers.
